name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deployment-job:

    runs-on: ubuntu-latest

    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        script: |
          cd ${{ secrets.WORKDIR }}
          source ./.venv/bin/activate
          pip install -r requirements.txt
          git reset --hard HEAD && git pull origin main
